version: '3.8'

services:
  web:
    image: josuechambilla/proyecto_codigo-web
    container_name: proyecto_codigo_web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: proyecto_codigo_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tienda_bd
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: proyecto_codigo_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
    depends_on:
      - db
