name: Create Release

on:
  workflow_run:
    workflows: ["Docker Image CI"]  # Nombre del primer workflow
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest Docker image tag
      id: get_latest_tag
      run: |
        # Este comando debería obtener la última etiqueta de Docker Hub
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage
        echo "LATEST_TAG=$(docker images --filter=reference='${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:*' --format '{{.Tag}}' | sort -V | tail -n 1)" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.LATEST_TAG }}  # Usa la etiqueta obtenida
        release_name: Release ${{ env.LATEST_TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
