name: DockerHub Deployment

on:
  workflow_run:
    workflows: ["SonarCloud Analysis"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:v${{ github.run_number }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:v${{ github.run_number }}

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Deploy the latest Docker image
      run: |
        echo "Pulling image: ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:v${{ github.run_number }}"
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:v${{ github.run_number }}
        docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/pgfanpage:v${{ github.run_number }}
