name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 13-aplicar-sonarqube
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '2 23 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      
      # Run Semgrep CI
      - run: semgrep ci
      
      # Generate JSON report if results exist
      - run: |
          if [ -f semgrep.sarif ]; then
            semgrep report --output=semgrep-report.json --format=json
          else
            echo "No results found to generate report."
          fi

      # Optionally, upload the JSON report to your repository
      - name: Commit JSON report
        run: |
          if [ -f semgrep-report.json ]; then
            git config --local user.email "jaechambilla@upt.pe"
            git config --local user.name "jaechambilla"
            git add semgrep-report.json
            git commit -m "Add Semgrep report"
            git push
          else
            echo "No JSON report to commit."
          fi
