name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 13-aplicar-sonarqube
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '2 23 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4

      # Run Semgrep CI and capture output
      - name: Run Semgrep CI
        id: semgrep
        run: |
          semgrep ci > semgrep-output.txt || true

      # Extract details and write to results.txt
      - name: Create results.txt
        run: |
          awk '/^[^ ]+\.php/{print $0}' semgrep-output.txt | sort -u > results.txt

      # Format results with descriptions
      - name: Format results.txt
        run: |
          echo "Vulnerabilities found:" > formatted-results.txt
          awk '/^[^ ]+\.php/ {
            split($0, a, " ");
            path = a[1];
            title = a[2];
            print "File: " path "\nTitle: " title "\n" >> formatted-results.txt
          }' semgrep-output.txt

      # Upload formatted-results.txt as an artifact
      - name: Upload formatted-results.txt
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-formatted-results
          path: formatted-results.txt
