name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 13-aplicar-sonarqube
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '2 23 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      
      # Run Semgrep CI and capture output
      - name: Run Semgrep CI
        id: semgrep
        run: |
          semgrep ci > semgrep-output.txt || true

      # Create an HTML report from the output
      - name: Create HTML report
        run: |
          echo "<html><body><h1>Vulnerabilities Found</h1><pre>" > semgrep-report.html
          cat semgrep-output.txt >> semgrep-report.html
          echo "</pre></body></html>" >> semgrep-report.html

      # Upload the HTML report as an artifact
      - name: Upload semgrep-report.html
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep-report.html
