name: Semgrep Scan

on:
  push:
    branches: [ "13-aplicar-sonarqube" ]
  pull_request:
    branches: [ "13-aplicar-sonarqube" ]

jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config semgrep.yml --include 'src/**/*.php' -o semgrep.sarif --verbose || { echo "Semgrep failed"; exit 1; }

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
