name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 13-aplicar-sonarqube
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '2 23 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      
      # Run Semgrep CI and capture output
      - name: Run Semgrep CI
        id: semgrep
        run: |
          semgrep ci > semgrep-output.txt || true

      # Create a results.txt from the output
      - name: Create formatted-results.txt
        run: |
          echo "Vulnerabilities found:" > formatted-results.txt
          cat semgrep-output.txt >> formatted-results.txt

      # Upload the formatted-results.txt as an artifact
      - name: Upload formatted-results.txt
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: formatted-results.txt
