name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - 13-aplicar-sonarqube
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '2 23 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      
      # Run Semgrep CI and redirect output to a file
      - run: |
          semgrep ci > semgrep-output.txt || true

      # Generate JSON report if results exist
      - run: |
          if [ -f semgrep-output.txt ]; then
            semgrep report --output=semgrep-report.json --format=json < semgrep-output.txt
          else
            echo "No results found to generate report."
          fi

      # Upload the JSON report as an artifact
      - name: Upload JSON report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.json
