name: Snyk Scan

on:
  push:
    branches:
      - 13-aplicar-sonarqube
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: pyfanpage  # Usa tu Organization slug aquí
        run: snyk test --all-projects --org=$SNYK_ORG

      - name: Monitor Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: pyfanpage  # Usa tu Organization slug aquí
        run: snyk monitor --all-projects --org=$SNYK_ORG
