name: Example workflow using Snyk

on:
  push:
    branches:
      - 13-aplicar-sonarqube # Reemplaza 'tu-rama' con el nombre de tu rama

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Cambia a la versi칩n m치s reciente
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v2 # Cambia a la versi칩n m치s reciente
        continue-on-error: true # Para asegurar que se llame a la carga de SARIF
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
