# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Snyk Container

on:
  push:
    branches: [ "13-aplicar-sonarqube" ]
  pull_request:
    branches: [ "13-aplicar-sonarqube" ]
  schedule:
    - cron: '18 23 * * 3'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for uploading results to Snyk
      actions: read # only required for a private repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build a Docker image
        run: docker build -t your/image-to-test .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: your/image-to-test
          args: --file=Dockerfile

      - name: Monitor image with Snyk
        run: snyk container monitor your/image-to-test --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to Snyk
        run: |
          echo "Results uploaded to Snyk"
