name: Example workflow using Snyk

on:
  push:
    branches:
      - 13-aplicar-sonarqube # Reemplaza con tu rama

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      
      - name: Upload Snyk SARIF file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-scan-results
          path: snyk.sarif

      - name: Print the Snyk SARIF file
        run: cat snyk.sarif
