name: SonarCloud Scan & Semgrep Analysis
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build and Run SonarCloud Scanner
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=pyfanpage \
          -Dsonar.organization=pyfanpage \
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Wait for SonarCloud analysis to finish
        run: |
          sleep 30  # Esperar a que el análisis se complete
          
      - name: Fetch Vulnerabilities
        run: |
          echo "## Vulnerabilities Detected"
          echo "| Message | Severity | Component | Line | Status |"
          echo "|---------|----------|-----------|------|--------|"
          curl -u "${{ secrets.SONAR_TOKEN }}: " "https://sonarcloud.io/api/issues/search?componentKeys=pyfanpage&types=VULNERABILITY" \
          | jq -r '.issues[] | "| \(.message) | \(.severity) | \(.component) | \(.line) | \(.status) |"'

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          python -m pip install semgrep

      - name: Semgrep Analysis
        run: |
          semgrep scan --config='p/default' --sarif --output=report.sarif
          echo "Scan Summary:"
          semgrep scan --config='p/default' --json | jq '.results[] | {language: .language, path: .path, message: .extra.message}'
