name: SonarCloud Scan & Semgrep Analysis
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Create reports directory
        run: mkdir -p reports

      - name: Build and Run SonarCloud Scanner
        id: sonar_scan
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=pyfanpage \
          -Dsonar.organization=pyfanpage \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=./src \  # Asegúrate de que apunta a la carpeta correcta
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.issuesReport.html.enable=true \
          -Dsonar.issuesReport.html.location=reports/sonar-report.html  # Ubicación del informe

      - name: List files in reports directory
        run: ls -la reports/

      - name: Wait for SonarCloud analysis to finish
        run: |
          sleep 60  # Aumentar el tiempo de espera

      - name: Commit and Push HTML Report
        run: |
          if [ -f reports/sonar-report.html ]; then
            git config --global user.name "JosueUPT"
            git config --global user.email "jaechambilla@upt.pe"
            git add reports/sonar-report.html
            git commit -m "Add SonarCloud report"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No report found, skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
