name: Tarea Automatizada de análisis de código

env:
  SONAR_ORG: 'pyfanpage'
  SONAR_PROJECT: 'pyfanpage'

on:
  push:
    branches:
      - "13-aplicar-sonarqube"
  workflow_dispatch:

jobs:
  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Build and Run SonarCloud Scanner
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT }} \
          -Dsonar.organization=${{ env.SONAR_ORG }} \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Obtener estado del análisis
        id: sonar_status
        run: |
          ANALYSIS_JSON=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT }}")
          echo "ANALYSIS_JSON=${ANALYSIS_JSON}" >> $GITHUB_ENV
          echo "Respuesta de la API: $ANALYSIS_JSON"  # Mostrar respuesta en logs

      - name: Generar reporte HTML
        run: |
          echo "<html><head><title>Reporte de SonarCloud</title></head><body>" > sonar_report.html
          echo "<h1>Reporte de Calidad para ${{ env.SONAR_PROJECT }}</h1>" >> sonar_report.html
          echo "<p>Estado: $(echo ${{ env.ANALYSIS_JSON }} | jq -r '.status')</p>" >> sonar_report.html
          echo "</body></html>" >> sonar_report.html

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: sonar-report
          path: sonar_report.html
