name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  sonarcloud:
    docker:
      image: "sonarsource/sonar-scanner-cli"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run SonarCloud Scanner
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=pyfanpage \
          -Dsonar.organization=tu_organizacion \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Wait for SonarCloud analysis to finish
        run: |
          sleep 60  # Esperar a que el análisis se complete

      - name: Display SonarCloud Report
        run: |
          echo "SonarCloud Report: https://sonarcloud.io/project/overview?id=pyfanpage"
